### ISSUE TITLE
How to design the PQMF filter.

### ISSUE THREAD

**Issue by MaNatsu8023** [haoheliu/Subband-Music-Separation#2]
I see your filter for PQMF is .m，could u open-source your Matlab code of how to design the filters? Thank u.

**Comment by haoheliu** [comment]
Thanks for reaching out. I use this open-source [MATLAB toolbox](https://www.mathworks.com/matlabcentral/fileexchange/40128-filter-bank-design.) It's the implementation of 
Moazzen, I. , Agathoklis, P., "A General Approach for Filter Bank Design Using Optimization", Technical Report, 2014.
Hope this would help.

**Comment by haoheliu** [comment]
> I see your filter for PQMF is .m，could u open-source your Matlab code of how to design the filters? Thank u.

Also, you can try [this method]( https://github.com/AppleHolic/pytorch_sound/blob/master/pytorch_sound/models/transforms.py#L382), but this one is much lossier and I still recommend the method we use in this project. 

Here is a comparison, the blue line is the original signal and the orange line is the reconstructed signal. The second figure shows the reconstruct result from the method we use in this project, which is more accurate.

![image](https://user-images.githubusercontent.com/42107684/94362207-55ff2b00-00ec-11eb-8ecf-ee3d087c11e5.png)

![image](https://user-images.githubusercontent.com/42107684/94362272-c9a13800-00ec-11eb-88e7-bdc6dbf974f3.png)
